import type { LevelDefinition } from "./types";

export const PUZZLE_START_DATE = new Date("2026-03-27T00:00:00Z");
const DAY_MS = 24 * 60 * 60 * 1000;

export interface PuzzleDefinition {
  level: LevelDefinition;
  solution: boolean[][];
}

export type PuzzleDifficulty = "easy" | "medium";

export const puzzles: PuzzleDefinition[] = [
  {"level":[[".","1",".",".",".",".","."],["1",".",".",".","2",".","1"],[".",".",".",".",".",".","."],[".",".",".",".","2",".","0"],["2","0",".",".",".","1","."],[".","2",".","0","2",".","."],["#",".","1","#",".",".","."]],"solution":[[true,false,false,true,false,false,false],[false,false,true,false,false,true,false],[false,false,false,false,true,false,false],[true,false,false,false,false,false,false],[false,false,false,false,true,false,false],[true,false,false,false,false,false,true],[false,true,false,false,true,false,false]]},
  {"level":[["0","#",".",".","0",".","."],[".",".",".",".","3",".","."],[".",".",".","2",".",".","0"],[".",".",".",".","1","0","."],["1","0",".",".",".","1","."],["1","1",".",".",".",".","."],[".",".",".",".",".",".","."]],"solution":[[false,false,false,false,false,false,true],[false,false,false,true,false,true,false],[false,true,false,false,true,false,false],[true,false,false,false,false,false,false],[false,false,false,true,false,false,true],[false,false,true,false,false,false,false],[true,false,false,false,false,false,false]]},
  {"level":[["#",".",".","0","1",".","1"],["1","#",".",".","1",".","."],[".",".","#","2",".",".","."],["2",".","2",".",".",".","."],[".",".","0","1",".",".","."],[".",".",".",".",".","0","."],[".","1",".",".",".",".","."]],"solution":[[false,true,false,false,false,true,false],[false,false,true,false,false,false,false],[true,false,false,false,true,false,false],[false,true,false,true,false,false,false],[false,false,false,false,false,false,true],[true,false,false,false,false,false,false],[false,false,true,false,false,false,false]]},
  {"level":[[".",".",".",".",".",".","."],["1",".","1",".",".",".","0"],[".",".",".",".",".",".","."],[".","#","1",".",".",".","."],["2",".",".",".",".",".","."],[".",".","1",".",".",".","."],[".",".","1","#","2",".","."]],"solution":[[true,false,false,false,false,false,false],[false,false,false,true,false,false,false],[false,true,false,false,false,false,false],[true,false,false,false,false,false,true],[false,false,true,false,false,false,false],[true,false,false,false,true,false,false],[false,true,false,false,false,true,false]]},
  {"level":[["0","2",".",".",".",".","."],[".",".",".",".",".","1","."],[".",".","#",".",".","#","."],["1","1",".","4",".",".","."],["0",".",".",".",".",".","."],[".",".",".",".",".",".","."],[".",".","1",".","0",".","."]],"solution":[[false,false,true,false,false,false,false],[false,true,false,false,false,false,true],[true,false,false,true,false,false,false],[false,false,true,false,true,false,false],[false,false,false,true,false,false,false],[false,false,false,false,false,true,false],[false,true,false,false,false,false,false]]},
  {"level":[["1","#","#","0",".",".","."],[".","1",".",".",".","#","2"],[".",".",".",".",".","1","."],["1",".","2",".",".",".","."],[".",".",".","#",".","2","."],[".",".",".","0",".",".","."],[".",".",".",".",".",".","."]],"solution":[[false,false,false,false,false,false,true],[true,false,false,false,false,false,false],[false,false,true,false,false,false,true],[false,false,false,true,false,false,false],[true,false,false,false,true,false,false],[false,true,false,false,false,true,false],[false,false,true,false,false,false,false]]},
  {"level":[[".","2","#",".",".",".","1"],[".",".",".","1",".",".","1"],["0","3",".",".","#",".","."],[".",".","3",".",".","#","1"],[".",".",".",".",".",".","."],["2",".",".",".",".",".","."],[".",".","0",".",".","1","1"]],"solution":[[true,false,false,false,false,true,false],[false,true,false,false,true,false,false],[false,false,true,false,false,false,true],[false,true,false,true,false,false,false],[true,false,false,false,false,false,false],[false,false,false,false,false,false,true],[true,false,false,false,true,false,false]]},
  {"level":[[".","2",".",".",".","1","."],[".",".",".",".",".",".","."],[".",".","0","0",".",".","1"],["0","0",".","2",".",".","."],["0","#",".",".",".","#","#"],[".",".",".","2",".",".","1"],["#",".",".",".",".",".","."]],"solution":[[true,false,false,true,false,false,true],[false,true,false,false,false,false,false],[false,false,false,false,false,true,false],[false,false,false,false,true,false,false],[false,false,false,true,false,false,false],[false,false,true,false,false,true,false],[false,true,false,false,false,false,false]]},
  {"level":[[".",".","1",".",".",".","."],[".",".",".","#",".",".","1"],[".","1",".","2",".","2","0"],["0",".",".",".","2",".","0"],["0","#",".",".",".",".","."],[".",".",".",".",".",".","."],[".","1",".",".",".","2","."]],"solution":[[true,false,false,true,false,false,false],[false,true,false,false,false,true,false],[false,false,false,false,true,false,false],[false,false,false,true,false,false,false],[false,false,false,false,false,true,false],[false,false,true,false,false,false,false],[true,false,false,false,true,false,true]]},
  {"level":[[".",".",".",".",".",".","."],[".","#",".","2","1",".","2"],[".",".","2","#","0",".","."],[".",".",".",".","#",".","."],[".",".","1","1",".",".","0"],[".",".",".",".",".","#","."],[".","0",".","0","0",".","."]],"solution":[[false,false,false,true,false,false,false],[false,false,true,false,false,true,false],[false,true,false,false,false,false,true],[true,false,false,false,false,false,false],[false,false,false,false,true,false,false],[false,false,true,false,false,false,false],[false,false,false,false,false,false,true]]},
  {"level":[[".",".",".",".",".","1","#"],[".",".","1","0",".",".","2"],[".",".","#",".",".",".","."],[".","2",".",".",".","1","."],[".",".","2",".",".",".","1"],[".","3",".",".",".",".","."],[".",".","#",".",".","0","1"]],"solution":[[false,false,true,false,false,false,false],[false,false,false,false,false,true,false],[false,true,false,false,false,false,true],[false,false,false,false,true,false,false],[false,true,false,true,false,false,false],[true,false,false,false,false,false,true],[false,true,false,false,false,false,false]]},
  {"level":[["0","0",".",".",".","1","1"],[".",".",".",".","1",".","."],[".","0",".",".",".",".","."],[".",".",".",".",".",".","."],[".",".","1",".",".",".","#"],[".","1",".",".",".",".","."],["0","#",".","1","2",".","."]],"solution":[[false,false,false,false,true,false,false],[false,false,true,false,false,false,true],[false,false,false,true,false,false,false],[true,false,false,false,false,false,false],[false,true,false,false,false,false,false],[false,false,false,false,true,false,false],[false,false,true,false,false,true,false]]},
  {"level":[["2",".","1",".",".",".","."],[".",".",".",".",".",".","."],["1",".",".",".",".",".","."],[".",".",".","4",".",".","."],[".",".",".",".","3","1","."],[".",".",".","#",".",".","#"],["1",".",".",".",".",".","1"]],"solution":[[false,true,false,false,false,true,false],[true,false,false,false,false,false,false],[false,false,false,true,false,false,false],[false,false,true,false,true,false,false],[false,false,false,true,false,false,true],[true,false,false,false,true,false,false],[false,false,false,false,false,true,false]]},
  {"level":[[".","1",".",".",".",".","."],[".","0",".","1",".","2","."],[".",".",".",".",".",".","1"],[".",".",".",".",".","1","."],["1","#",".","1",".",".","."],[".",".",".","0","1",".","."],["2",".","1","1",".",".","1"]],"solution":[[false,false,true,false,false,false,false],[false,false,false,false,true,false,true],[true,false,false,false,false,false,false],[false,false,false,true,false,false,false],[false,false,false,false,false,true,false],[true,false,false,false,false,false,true],[false,true,false,false,true,false,false]]},
  {"level":[[".",".",".","3",".",".","0"],[".",".",".",".","4",".","."],[".",".","0","3",".",".","."],[".","0","2",".",".",".","."],[".","2",".",".","0","0","."],[".",".",".",".",".","#","."],[".","#",".",".",".","1","#"]],"solution":[[false,false,true,false,true,false,false],[false,false,false,true,false,true,false],[true,false,false,false,true,false,false],[false,false,false,true,false,false,false],[false,false,true,false,false,false,false],[false,true,false,false,false,false,true],[false,false,false,false,true,false,false]]},
  {"level":[[".",".","2",".",".","0","."],[".",".",".",".","0",".","."],["1",".","3",".",".",".","."],[".",".",".",".",".","1","#"],[".",".",".",".",".",".","."],[".","1","#","#",".",".","."],[".","1",".","1","2",".","."]],"solution":[[true,false,false,true,false,false,false],[false,false,true,false,false,false,true],[false,true,false,false,false,true,false],[false,false,true,false,false,false,false],[false,false,false,false,false,false,true],[true,false,false,false,true,false,false],[false,false,true,false,false,true,false]]},
  {"level":[["1",".",".","1",".",".","."],["#",".",".",".",".","2","."],[".",".",".",".",".",".","."],[".","1",".",".",".","1","."],[".","1",".","2",".","2","."],[".",".",".",".",".","1","."],[".",".","1",".",".",".","."]],"solution":[[false,true,false,false,false,true,false],[false,false,false,true,false,false,false],[false,false,false,false,false,true,false],[false,false,true,false,false,false,false],[true,false,false,false,true,false,true],[false,false,false,true,false,false,false],[false,true,false,false,false,true,false]]},
  {"level":[[".","1",".",".",".",".","."],["#",".",".","1",".",".","."],[".",".",".",".",".","1","."],[".",".","3",".","1","0","."],["2",".",".",".",".",".","."],[".",".",".",".","1",".","."],[".",".","1",".",".",".","1"]],"solution":[[true,false,false,true,false,false,false],[false,false,false,false,false,true,false],[false,false,true,false,false,false,false],[true,false,false,true,false,false,false],[false,false,true,false,false,false,false],[true,false,false,false,false,false,true],[false,true,false,false,true,false,false]]},
  {"level":[[".","0","#",".",".","#","0"],[".",".",".","0","#",".","#"],[".",".",".",".",".",".","#"],[".",".",".","3",".",".","."],[".",".","3",".",".","1","."],["1",".",".",".",".",".","1"],[".",".","1",".",".",".","."]],"solution":[[false,false,false,false,true,false,false],[true,false,false,false,false,true,false],[false,true,false,false,false,false,false],[false,false,true,false,true,false,false],[false,false,false,true,false,false,true],[false,false,true,false,false,false,false],[true,false,false,false,false,true,false]]},
  {"level":[[".",".",".",".","2",".","."],["3",".",".",".","0",".","."],[".",".",".",".",".",".","."],["#",".","0",".",".",".","#"],["#","0",".",".","1",".","1"],[".",".",".",".",".",".","."],[".",".",".",".",".",".","."]],"solution":[[false,false,true,false,false,false,true],[false,true,false,false,false,false,false],[true,false,false,false,false,false,false],[false,false,false,false,true,false,false],[false,false,false,false,false,false,false],[false,false,false,false,false,false,true],[false,false,true,false,false,false,false]]},
  {"level":[[".",".","1",".",".",".","."],[".",".",".","1",".",".","."],[".",".",".",".","1",".","."],[".",".","1",".",".",".","."],[".","1",".",".",".",".","."],[".",".",".","1",".",".","1"],[".",".",".",".","1",".","."]],"solution":[[true,false,false,false,true,false,false],[false,true,false,false,false,true,false],[false,false,true,false,false,false,true],[false,false,false,true,false,false,false],[false,true,false,false,false,true,false],[true,false,false,false,false,false,false],[false,false,false,true,false,false,true]]},
  {"level":[[".","1",".",".",".",".","."],[".",".",".",".","1","0","."],[".",".",".",".",".",".","1"],[".",".",".","1",".",".","."],["1",".",".",".",".",".","."],[".",".",".",".","1",".","."],[".","1",".",".",".",".","1"]],"solution":[[false,false,true,false,false,false,false],[true,false,false,false,false,false,false],[false,false,false,true,false,true,false],[false,false,false,false,false,false,true],[false,true,false,false,true,false,false],[true,false,false,false,false,false,false],[false,false,false,true,false,false,true]]},
  {"level":[[".",".",".",".","1",".","."],[".","1",".",".",".",".","."],[".",".","1",".",".",".","."],[".",".",".",".","1",".","."],[".","1",".",".",".",".","."],[".",".",".",".","1",".","."],[".",".","1",".",".","1","."]],"solution":[[true,false,false,false,false,false,true],[false,false,true,false,false,true,false],[false,true,false,false,true,false,false],[false,false,false,true,false,false,true],[false,true,false,false,true,false,false],[true,false,false,false,false,false,false],[false,false,true,false,true,false,false]]},
  {"level":[[".",".","1",".",".",".","0"],[".",".",".","0",".","1","."],[".",".",".",".",".",".","."],[".","1",".",".",".",".","."],["1",".",".",".",".",".","."],[".",".",".","1",".",".","."],[".",".",".",".","1",".","."]],"solution":[[false,false,true,false,false,false,false],[true,false,false,false,false,false,true],[false,false,false,true,false,false,false],[false,true,false,false,false,false,false],[false,false,false,true,false,false,false],[true,false,false,false,false,false,false],[false,false,false,false,true,false,true]]},
  {"level":[[".",".",".","1",".",".","."],[".","1",".",".",".",".","."],[".",".",".",".","1",".","."],[".",".","1",".",".",".","."],[".","1",".",".",".",".","."],[".",".",".","1",".",".","."],[".",".","1",".",".",".","1"]],"solution":[[false,true,false,false,false,false,true],[true,false,false,true,false,false,false],[false,false,true,false,false,true,false],[false,false,false,true,false,false,false],[false,true,false,false,false,true,false],[true,false,false,false,true,false,false],[false,false,true,false,false,false,true]]},
  {"level":[[".",".",".",".","1",".","."],[".",".",".",".",".",".","."],[".",".","1",".",".",".","."],[".",".",".",".","1",".","."],[".","1",".",".",".",".","."],[".",".",".",".","1",".","."],[".",".","1",".",".",".","1"]],"solution":[[true,false,false,false,false,false,true],[false,false,true,false,false,true,false],[false,true,false,false,true,false,false],[false,false,false,true,false,false,true],[false,true,false,false,true,false,false],[true,false,false,false,false,false,false],[false,false,true,false,true,false,false]]},
  {"level":[[".",".","1",".",".",".","0"],[".",".",".","0",".","1","."],[".",".",".",".",".",".","."],[".","1",".",".",".",".","."],["1",".",".",".",".",".","."],[".",".",".","1",".",".","."],[".",".",".",".","1",".","."]],"solution":[[false,false,true,false,false,false,false],[true,false,false,false,false,false,true],[false,false,false,true,false,false,false],[false,true,false,false,false,false,false],[false,false,false,true,false,false,false],[true,false,false,false,false,false,false],[false,false,false,false,true,false,true]]},
  {"level":[[".",".",".","1",".",".","."],[".","1",".",".",".",".","."],[".",".",".",".","1",".","."],[".",".","1",".",".",".","."],[".","1",".",".",".",".","."],[".",".",".","1",".",".","."],[".",".","1",".",".",".","1"]],"solution":[[false,true,false,false,false,false,true],[true,false,false,true,false,false,false],[false,false,true,false,false,true,false],[false,false,false,true,false,false,false],[false,true,false,false,false,true,false],[true,false,false,false,true,false,false],[false,false,true,false,false,false,true]]},
  {"level":[[".",".",".",".","1",".","."],[".",".",".",".",".",".","."],[".",".","1",".",".",".","."],[".",".",".",".","1",".","."],[".","1",".",".",".",".","."],[".",".",".",".","1",".","."],[".",".","1",".",".",".","1"]],"solution":[[true,false,false,false,false,false,true],[false,false,true,false,false,true,false],[false,true,false,false,true,false,false],[false,false,false,true,false,false,true],[false,true,false,false,true,false,false],[true,false,false,false,false,false,false],[false,false,true,false,true,false,false]]},
  {"level":[[".",".","1",".",".",".","0"],[".",".",".","0",".","1","."],[".",".",".",".",".",".","."],[".","1",".",".",".",".","."],["1",".",".",".",".",".","."],[".",".",".","1",".",".","."],[".",".",".",".","1",".","."]],"solution":[[false,false,true,false,false,false,false],[true,false,false,false,false,false,true],[false,false,false,true,false,false,false],[false,true,false,false,false,false,false],[false,false,false,true,false,false,false],[true,false,false,false,false,false,false],[false,false,false,false,true,false,true]]}
];

export function getPuzzleDifficulty(index: number): PuzzleDifficulty {
  return index < 15 ? "easy" : "medium";
}

export function toUtcDateString(date: Date) {
  const utc = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()));
  return utc.toISOString().slice(0, 10);
}

export function getPuzzleIndexForDate(date: Date) {
  const start = Date.UTC(
    PUZZLE_START_DATE.getUTCFullYear(),
    PUZZLE_START_DATE.getUTCMonth(),
    PUZZLE_START_DATE.getUTCDate()
  );
  const target = Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate());
  const diff = Math.floor((target - start) / DAY_MS);
  if (diff < 0 || diff >= puzzles.length) {
    return null;
  }
  return diff;
}

export function getDateForPuzzleIndex(index: number) {
  const start = Date.UTC(
    PUZZLE_START_DATE.getUTCFullYear(),
    PUZZLE_START_DATE.getUTCMonth(),
    PUZZLE_START_DATE.getUTCDate()
  );
  return new Date(start + index * DAY_MS);
}
